# Exported from Render on 2026-09-28T11:14:03Z
version: "1"
services:
- type: web
  name: bioherd-api
  runtime: python
  repo: https://github.com/Nithinhelloweb/BIOHERD
  plan: free
  envVars:
  - key: CORS_ORIGINS
    sync: false
  - key: DATABASE_URL
    sync: false
  - key: SECRET_KEY
    sync: false
  - key: DEBUG
    sync: false
  - key: ENVIRONMENT
    sync: false
  - key: PYTHON_VERSION
    sync: false
  region: oregon
  buildCommand: pip install --upgrade pip && pip install -r requirements.txt
  startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT --proxy-headers --forwarded-allow-ips='*'
  healthCheckPath: /api/v1/health/liveness
  autoDeployTrigger: commit
  rootDir: backend
